remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme

title: Khulumni e.V.
description: Alumni- und Förderverein der Fachschaftsvertretung der Fachschaft Humanwissenschaften der Otto-Friedrich-Universität Bamberg
show_downloads: false

# Just the Docs Konfiguration
color_scheme: light
search_enabled: true
heading_anchors: true
aux_links:
  "Fachschaft HuWi":
    - "https://www.uni-bamberg.de/huwi/personen-und-einrichtungen/fachschaft-huwi/"

# Logo Konfiguration
logo: "/assets/logo.png"

